const db=window.supabase.createClient(window.STORE_SUPABASE_URL,window.STORE_SUPABASE_PUBLISHABLE_KEY),$=s=>document.querySelector(s),msg=(s,t,e=false)=>{const n=$(s);n.textContent=t;n.style.color=e?'#b42318':'#27703b'};
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function owner(){const{data:{user}}=await db.auth.getUser();if(!user)return false;const{data}=await db.from('profiles').select('role').eq('id',user.id).maybeSingle();return data?.role==='owner'}
async function products(){const{data}=await db.from('products').select('*').order('created_at',{ascending:false});$('#productList').innerHTML=data?.length?data.map(p=>`<div class="item"><img src="${p.image_urls?.[0]||''}" alt=""><div><strong>${esc(p.name)}</strong><p>₹${p.price||'—'} · ${esc(p.category)}</p></div><button class="delete" data-id="${p.id}">Delete</button></div>`).join(''):'<p>No products yet.</p>';document.querySelectorAll('.delete[data-id]').forEach(b=>b.onclick=async()=>{await db.from('products').delete().eq('id',b.dataset.id);products()})}
async function settings(){const{data}=await db.from('store_settings').select('*').eq('id',true).maybeSingle();if(data)Object.entries(data).forEach(([k,v])=>{$('#settingsForm').elements[k]&&($('#settingsForm').elements[k].value=v||'')})}
async function offers(){const{data}=await db.from('offers').select('*').order('created_at',{ascending:false});$('#offerList').innerHTML=data?.map(o=>`<div class="item"><div><strong>${esc(o.title)}</strong><p>${esc(o.details)}</p></div><button class="delete" data-offer="${o.id}">Delete</button></div>`).join('')||'';document.querySelectorAll('[data-offer]').forEach(b=>b.onclick=async()=>{await db.from('offers').delete().eq('id',b.dataset.offer);offers()})}
async function dashboard(){$('#login').hidden=true;$('#panel').hidden=false;await Promise.all([products(),settings(),offers()])}
$('#loginForm').onsubmit=async e=>{e.preventDefault();const{error}=await db.auth.signInWithPassword({email:$('#email').value,password:$('#password').value});if(error)return msg('#loginMsg',error.message,true);if(!await owner()){await db.auth.signOut();return msg('#loginMsg','This is not an owner account.',true)}dashboard()};
$('#signOut').onclick=async()=>{await db.auth.signOut();location.reload()};document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('article').forEach(x=>x.hidden=true);b.classList.add('active');$('#'+b.dataset.target).hidden=false});
$('#productForm').onsubmit=async e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.target)),urls=[];msg('#productMsg','Uploading…');for(const f of $('#photos').files){const path=`${crypto.randomUUID()}-${f.name.replace(/[^\w.-]/g,'-')}`,{error}=await db.storage.from('product-images').upload(path,f);if(error)return msg('#productMsg',error.message,true);urls.push(db.storage.from('product-images').getPublicUrl(path).data.publicUrl)}const{error}=await db.from('products').insert({name:v.name,price:v.price||null,category:v.category||null,sizes:v.sizes?v.sizes.split(',').map(x=>x.trim()):[],description:v.description||null,image_urls:urls});if(error)return msg('#productMsg',error.message,true);e.target.reset();msg('#productMsg','Product added.');products()};
$('#settingsForm').onsubmit=async e=>{e.preventDefault();const{error}=await db.from('store_settings').upsert({id:true,...Object.fromEntries(new FormData(e.target))});msg('#settingsMsg',error?error.message:'Saved.',!!error)};
$('#offerForm').onsubmit=async e=>{e.preventDefault();const{error}=await db.from('offers').insert(Object.fromEntries(new FormData(e.target)));if(!error)e.target.reset();msg('#offerMsg',error?error.message:'Offer published.',!!error);offers()};owner().then(x=>x&&dashboard());
