const fallback = { brandName: 'Anand Adda', heroText: 'Fresh everyday styles, handpicked for your street, your plans and your personality.', offerTitle: 'Your next favourite fit is waiting.', offerText: 'Add your sale, festive offer or new-arrival announcement here.', shopTitle: 'The neighbourhood’s style stop.', shopDescription: 'Anand Adda is a welcoming local clothing shop where you can discover easy, confident fashion in person.', knownFor: 'Fresh local styles', perfectFor: 'Youthful everyday fashion', hours: '10:00 AM – 9:00 PM', address: 'Add full shop address from the owner panel.', phone: '', whatsapp: '', instagram: '@yourshop', mapUrl: 'https://maps.google.com' };
const data = { ...fallback, ...JSON.parse(localStorage.getItem('storeData') || '{}') };
const text = (id, value) => { const node = document.getElementById(id); if (node) node.textContent = value; };
text('brandName', data.brandName); text('footerBrand', data.brandName); text('heroText', data.heroText); text('offerTitle', data.offerTitle); text('offerText', data.offerText); text('shopTitle', data.shopTitle); text('shopDescription', data.shopDescription); text('knownFor', data.knownFor); text('perfectFor', data.perfectFor); text('hours', data.hours); text('address', data.address); text('phoneText', data.phone || 'Add phone number'); text('instagramText', data.instagram);
document.getElementById('phoneLink').href = data.phone ? `tel:${data.phone.replace(/\s/g, '')}` : '#contact';
document.getElementById('whatsappLink').href = data.whatsapp ? `https://wa.me/${data.whatsapp.replace(/\D/g, '')}` : '#contact';
document.getElementById('instagramLink').href = data.instagram && data.instagram !== '@yourshop' ? `https://instagram.com/${data.instagram.replace('@','')}` : '#contact';
document.getElementById('mapLink').href = data.mapUrl || fallback.mapUrl;
const menu = document.querySelector('.menu-button'), nav = document.querySelector('.main-nav');
menu.addEventListener('click', () => { const open = nav.classList.toggle('open'); menu.setAttribute('aria-expanded', open); });
nav.querySelectorAll('a').forEach(a => a.addEventListener('click', () => nav.classList.remove('open')));
